### ISSUE TITLE
record_get_field for field_position_global=0

### ISSUE THREAD

**Issue by ksachs** [inspirehep/invenio#244]
https://github.com/inspirehep/invenio/blob/prod/modules/bibrecord/lib/bibrecord.py#L668

How do I get the field at global_field_position = 0, if I can't get into this if-block (since 0 = False)
elif field_position_global:
-> 
elif field_position_global is not None:

Same for record_replace_field

Looks as if no one is using these functions.
I would call it a bug.

**Comment by tsgit** [comment]
I believe globalpos is either -1, None, or >=1 but not 0.

do you have an example of a recstruct where globalpos == 0 ?

it is true that globalpos 0 isn't explicitly excluded by docstrings, but it
doesn't show up in existing records
(maybe simply because it can't be set to 0? -- but then you also don't need
to access it?)

In [39]: from invenio.search_engine import get_collection_reclist

In [40]: heprecs=get_collection_reclist('HEP')

In [41]: globalpos=set()

In [42]: for r in heprecs:
   .....:     for f in get_record(r).values():
   .....:         for g in f:
   .....:             globalpos.add(g[-1])
   .....:

In [43]: min(globalpos)
1

bug or feature?
T.

**Comment by ksachs** [comment]
I got lost in the various positions in bibcheck and bibrecord. 
In the end I can't use it anyhow. Maybe feature.
record_add_field, record_delete_field, record_delete_subfield_from could handle globalpos=0.

**Comment by kaplun** [comment]
Mmm. But the positions in recstruct start with 1 :smile: What would be the semantic of position 0?

**Comment by kaplun** [comment]
As discussed offline I am closing this ticket.
